name: 'pre-release'

on:
  push:
    branches:
      - 'dev'
      - 'master'
    tags-ignore:
      - 'v*'
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  build:
    name: 'Create Release'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2.3.4'
        with:
          lfs: true
          fetch-depth: 0

      - id: 'yarn-cache'
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: 'actions/cache@v2.1.6'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - run: 'npm install --frozen-lockfile'
      # - run: 'yarn lint'

      - name: 'Create release'
        id: 'create_release'
        uses: 'actions/create-release@v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            -
            ${{ github.event.inputs.body }}
          draft: true
          prerelease: true
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes
            - Added a feature
            - Fixed a bug

      - name: Publish release
        if: github.event.push.commits.length == 0
        id: publish_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes
            - Added a feature
            - Fixed a bug
            ## Authors
            - Author: Author Name <author.email@example.com>
            - Author: Another Author <another.author.email@example.com>

